server:
  port: 8080

spring:
  application:
    name: myEcommerceShop
  devtools:
    add-properties: false
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  profiles:
    active: dev